name: Hodinovac
version: 'v1.0'
main: me.itzstanleex.hodinovac.Hodinovac
api-version: '1.21'
description: Advanced playtime tracking plugin with AFK detection and MySQL storage
softdepend: [PlaceholderAPI]